### ISSUE TITLE
Calculate volume and bounding box

### ISSUE THREAD

**Issue by alra7il** [johannesboyne/node-stl#11]
not considered min or max can be a negative number.
if (max x < 0 || min x > 0) {
  return max x - min x
}
return Math.abs(min x) + max x
in stead of max x - min x

Also, the volume value calculated by node stl is different with cura or admesh result! and the returned value is not reasonable in some cases

**Comment by redwildfire13** [comment]
Don't forget that volume is in units, not inches or millimeters. I've noticed that some programs export as mm even after working in inches which creates very large numbers for files designed in inches

**Comment by alra7il** [comment]
what kind of units?
in this link: https://www.npmjs.com/package/node-stl#example explained that unit is cm3

**Comment by redwildfire13** [comment]
The example is misleading. Stl is technically unit less. Dimensions can by something like 20x30x8 but it is impossible to tell if it is supposed to be mm or inches or anything. As a user, you can make sure that you export your files in the desired units, but even that is not 100% guarenteed. I currently use a software to convert sldprt (solidworks files) to stl and it regularly converts them as mm instead of the inches that the sldprt was designed in.

**Comment by alra7il** [comment]
After the above change, the bounding box value is correct in mm. it means x, y, z units in stl are mm.
 so I think volume value should be in the mm3 unit.

**Comment by johannesboyne** [comment]
Thanks for the great discussion. Do we get any action items out of this or does one might want to contribute via a PR?

**Comment by johannesboyne** [comment]
The PR #12 didn't fix this, or at least broke the test cases.

**Comment by johannesboyne** [comment]
@alra7il I guess, based on your comment in PR #12 this can be closed. Feel free to re-open if otherwise.
