### ISSUE TITLE
a method in order to determine if stl is a closed mesh or not

### ISSUE THREAD

**Issue by gokhangulgezen** [johannesboyne/node-stl#32]

**Comment by gokhangulgezen** [comment]
Hi to all.
Would it be a cool feature to add the a method whether to determine if stl is a closed mesh or not?
what do you say ?

**Comment by johannesboyne** [comment]
Hi @gokhangulgezen sounds like a nice feature, feel free to raise a PR!

**Comment by gokhangulgezen** [comment]
Hi @johannesboyne 
Do you think would it be a good idea to detect duplicate and unpaired edges or the code should just return whether stl is watertight or not ?
Such information might be useful in some cases but of course your opinion matters when it is come to the scope of the purpose of the code.

**Comment by johannesboyne** [comment]
I have not used the `stl` library myself for a while, just because I moved out of the space I was in before, and do not need it currently. Thus, I'm open for any suggestion.
Regarding your question: I would assume, it's much more straight forward to detect whether it's closed or not. I remember some `stl`s that where very freaky drawn, with a lot of duplicate edges, even though it was (for the use case) not a problem.

**Comment by johannesboyne** [comment]
Closed in https://github.com/johannesboyne/node-stl/pull/37

**Comment by gokhangulgezen** [comment]
actually you are right about duplicate edges. Even duplicate triangles might not be a problem for printing some stl files. I considered them not watertight because they can mislead the volume calculation and maybe even pricing if it is done according to volume. thanks for approving PR.
